app/cart/urls.py
from django.urls import path
from . import views

app_name='cart'


urlpatterns = [
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_deatil,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),
]

app/flowershopproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('shopapp.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls')),
    path('credential/',include('credential.urls')),
    path('payments/',include('payments.urls')),
    path('subscription_app/',include('subscription_app.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app/subscription_app/urls.py
from django.urls import path
from . import views
from .views import Pausepayment

app_name='subscription_app'


urlpatterns=[
    path('index', views.index, name='index'),
    path('auth/settings', views.settings, name='settings'),
    path('join',views.join,name='join'),
    path('checkout',views.checkout,name='checkout'),
    path('success',views.success,name='success'),
    path('canceled',views.canceled,name='canceled'),
    path('pausepayment',views.Pausepayment, name="pausepayment"),
    path('Resumepayment', views.Resumepayment, name='Resumepayment'),
    path('delete',views.delete,name='delete'),
    path('Updatesubscription',views.Updatesubscription,name='Updatesubscription'),



]

app/templates/membership/base1.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Flowers Cloud Home Lab</title>
 <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %} {% endblock %}</title>

  </head>
  <body>

      <div class="container">
    {% include 'header.html' %}
    {% include 'nav.html' %}
    {% block content %}
    {% endblock %}
</div>
    {% include 'footer.html' %}


</body>
<!--<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">-->
<!--      <br><br>-->
<!--      <h5 class="my-0 mr-md-auto font-weight-normal"><a href="{% url 'subscription_app:index' %}" class="text-dark">Flowers Cloud Home Lab</a></h5>-->
<!--      <nav class="my-2 my-md-0 mr-md-3">-->
<!--        {% if user.is_authenticated %}-->
<!--          <a class="p-2 text-dark" href="{% url 'subscription_app:settings' %}">Settings</a>-->
<!--          <a class="p-2 text-dark" href="{% url 'LogoutView' %}">Log Out</a>-->
<!--        {% else %}-->
<!--          <a class="p-2 text-dark" href="{% url 'LoginView' %}">Log In</a>-->
<!--        {% endif %}-->
<!--      </nav>-->
<!--      {% if user.is_authenticated == False %}-->
<!--      <a class="btn btn-outline-primary" href="">Sign up</a>-->
<!--      {% endif %}-->
<!--    </div>-->
</html>

app/templates/membership/cancel.html
{% extends 'membership/base1.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">Flowers  Home Lab Premium</h1>
</div>

<div class="container">
   Your subscription is canceled<br>
    Your subscription will run to the end of your billing cycle.
</div>
{% endblock %}

app/templates/membership/checkout.html
{% extends 'membership/base1.html' %}
{% block content %}
<div class="container">
  <div class="row justify-content-center">
      <div class="col-md-4 order-md-2 mb-4">
        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="text-muted">Your cart</span>
          <span class="badge badge-secondary badge-pill">1</span>
        </h4>
        <ul class="list-group mb-3">
          <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
              <h6 class="my-0">Cloud Home Lab Premium</h6>
              <small class="text-muted">{{ membership | title }}</small>
            </div>
          </li>
          <li class="list-group-item d-flex justify-content-between">
            <span>Total (INR)</span>
            <strong>${{ final_dollar }}</strong>
          </li>
        </ul>

        <div class="text-center pt-3">

          <script src="https://js.stripe.com/v3/"></script>

            <button id="checkout-button" data-secret="{{ session_id }}">
              Checkout
            </button>

         {% load static %}
          <script type="text/javascript">
            var sessionid = "{{session_id}}";
          </script>
          <script src="{% static 'js/checkout.js' %}"></script>
        </div>
        </div>
      </div>


 </div>
{% endblock %}

app/templates/membership/delete.html
{% extends 'membership/base1.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">Cloud Home Lab Premium</h1>
</div>

<div class="container">
    Delete subscription permenantly
</div>
<a href="{% url 'subscription_app:settings' %}">back to settings</a>.

{% endblock %}

app/templates/membership/index.html
{% extends 'membership/base1.html' %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">

</div>

<div class="container">

  <h3>Welcome to your home page</h3>
  <ul>

  </ul>
</div>
{% endblock %}

app/templates/membership/join.html
{% extends 'membership/base1.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">Cloud Home Lab Premium</h1>
</div>

<div class="container">
  <div class="card-deck mb-3 text-center">
    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Monthly</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">500₹ <small class="text-muted">/ mo</small></h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>Premium Access</li>
        </ul>
        <a href="{% url 'subscription_app:checkout' %}?membership=monthly"><button type="button" class="btn btn-lg btn-block btn-outline-primary">Get started</button></a>
      </div>
    </div>
    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Yearly<small class="text-primary">  Save 20₹!</small></h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">1000₹ <small class="text-muted">/ yr</small></h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>Premium Access</li>
        </ul>
        <a href="{% url 'subscription_app:checkout' %}?membership=yearly"><button type="button" class="btn btn-lg btn-block btn-primary">Get started</button></a>
      </div>

    </div>
  </div>
</div>
{% endblock %}

app/templates/membership/pause.html
{% extends 'membership/base1.html' %}

{% block content %}
<h1>Subscription Paused</h1>
<a href="{% url 'subscription_app:settings' %}">back to settings</a>.
{% endblock %}

app/templates/membership/resume.html
{% extends 'membership/base1.html' %}

{% block content %}
<h1>Subscription Resumed</h1>
<a href="{% url 'subscription_app:settings' %}">back to settings</a>.

{% endblock %}

app/templates/membership/success.html
{% extends 'membership/base1.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">Cloud Home Lab Premium</h1>
</div>

<div class="container">
    Welcome
</div>
<a href="{% url 'subscription_app:settings' %}">back to settings</a>.
{% endblock %}

app/templates/membership/update.html
{% extends 'membership/base1.html' %}

{% block content %}
<h1>Subscription updated successfully</h1>
<a href="{% url 'subscription_app:settings' %}">back to settings</a>.

{% endblock %}