app/cart/urls.py
from django.urls import path
from . import views

app_name='cart'


urlpatterns = [
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_deatil,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),
]

app/flowershopproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('shopapp.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls')),
    path('credential/',include('credential.urls')),
    path('payments/',include('payments.urls')),
    path('subscription_app/',include('subscription_app.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app/payments/urls.py
from django.urls import path
from payments.views import PaymentSuccessView, CancelView, CreateCheckoutSessionView
app_name='payments'

urlpatterns=[

    path('api/checkout-session/', CreateCheckoutSessionView.as_view(), name='checkout_session'),

    path('cancel/', CancelView.as_view(), name='cancel'),
    path('successpage/', PaymentSuccessView.as_view(), name='successpage'),
]

app/search_app/urls.py
from django.urls import path
from . import views
app_name='search_app'

urlpatterns = [
    path('',views.SearchResult.as_view(),name='SearchResult'),
]

app/shopapp/urls.py
from django.urls import path
from . import views
app_name='shopapp'

urlpatterns = [
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.proDetail,name='proCatdetail'),
]

app/subscription_app/urls.py
from django.urls import path
from . import views
from .views import Pausepayment

app_name='subscription_app'


urlpatterns=[
    path('index', views.index, name='index'),
    path('auth/settings', views.settings, name='settings'),
    path('join',views.join,name='join'),
    path('checkout',views.checkout,name='checkout'),
    path('success',views.success,name='success'),
    path('canceled',views.canceled,name='canceled'),
    path('pausepayment',views.Pausepayment, name="pausepayment"),
    path('Resumepayment', views.Resumepayment, name='Resumepayment'),
    path('delete',views.delete,name='delete'),
    path('Updatesubscription',views.Updatesubscription,name='Updatesubscription'),



]

app/cart/models.py
from django.db import models
from shopapp.models import Product


# Create your models here.

class Cart(models.Model):
    objects = None
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)


class CartItem(models.Model):
    objects = None
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = "CartItem"

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

app/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shopapp.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
from django.views.generic import View


# Create your views here.
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


# class _cart_id(View):
#   def POST(self,request):
#     cart = request.session.session_key
#     if not cart:
#         cart = request.session.create()
#     return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product=product, quantity=1, cart=cart)
    return redirect('cart:cart_detail')


def cart_deatil(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity

        request.session['total'] = int(total)

    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
<div class="container">
    {% include 'header.html' %}
    {% include 'nav.html' %}
    {% block content %}
    {% endblock %}
</div>
    {% include 'footer.html' %}

</body>
</html>

app/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    This is the cart page proceed to review your items and place the order
{% endblock %}

{% block title %}
   Cart-All In Bloom Company PVT LTD
{% endblock %}

{% block content %}
{% if not cart_items %}
<div>

    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your Shopping Cart is empty</h1>
        <p class="text-center">Please Click<a href="{% url 'shop:allProdCat' %}">Here</a>to continue shopping </p>

    </div>
</div>
{% else %}

<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my=title">Your Shopping Cart</h1>
        <br>
    </div>
    <div class="row mx-auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_thead">
                <tr>
                    <th colspan="5">Your Items</th>
                </tr>
                </thead>
                <tbody>
                {% for cart_item in cart_items %}
                <tr>
                   <td>
                       <a href=""><img src="{{cart_item.product.img.url}}" alt="" style="width:250px;height:200px;" class="float-left rounded custom_image"> </a>
                   </td>
                    <td class="text-left">
                        {{cart_item.product.name}}
                        <br>
                        SKU: {{cart_item.product.id}}
                        <br>
                        Price: ${{cart_item.product.price}}
                        <br>
                        Qty: {{cart_item.quantity}} x ${{cart_item}}
                    </td>
                    <td>
                        ${{cart_item.sub_total}}
                    </td>

                    {% if cart_item.quantity < cart_item.product.stock %}
                    <td>
                        <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa fa-plus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-trash custom_icon"></i></a>
                    </td>
                    {% else %}
                    <td>
                        &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-trash custom_icon"></i></a>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_thead">
                <tr>
                    <th>Checkout</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        Please review your shopping cart items before proceeding with the order payment.
                    </td>
                </tr>
                <tr>
                    <td class="text-left">
                        Your Total is:<strong>{{total}}</strong>
                    </td>
                </tr>
                </tbody>
            </table>

            <div class="mx_auto">

                <a href="{% url 'shopapp:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>

                <form action="{% url 'payments:checkout_session' %}" method="POST">
                    {% csrf_token %}
                    <button class="btn btn-primary" type="submit">Checkout</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endif %}
<br>
<br>
<br>
{% endblock %}

app/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   {% if category %}
     {{category.desc|truncatewords:155}}
   {% else %}
    Welcome to All In Bloom Collections where you can buys different items...
   {% endif %}
{% endblock %}

{% block title %}
  {% if category %}
     {{category.name}} - All in Bloom Collections
  {% else %}
  See our New Collections - All in Bloom Collections
  {% endif %}
{% endblock %}
{% block content %}
   {% if category %}
    <div>
        <div class="row my_row_class">
            <div class="mx_auto">
            <p><a href="{% url 'shopapp:allProdCat' %}">Our Product Collections</a></p>
            </div>
        </div>
    </div>
    {% endif %}

    <div class="mx_auto">
        {% if category %}
        <img class="my_image my_image_padding" src="{{category.img.url}}" alt="{{category.name}}" style="width:1300px;height:550px;">
    </div>
<br>
<div>
    <h1 class="text-center my_title">{{category.name}}</h1>
    <p class="text-justify">{{category.desc}}</p>

</div>

     {% else %}
<div>
    <img class="my_image my_image_padding" src="{% static 'img/Banner.png' %}" alt="Our Products" style="width:1120px;height:550px;">
</div>
<br>

<div>
    <h1 class="text-center my_title">Our Product Collections</h1>
    <p class="text-justify">A shopping cart known by a variety of other names, is a wheeled cart supplied by a shop or store, especially supermarkets, for use by customers inside the premises for transport of merchandise as they move around the premises, while shopping, prior to heading to the checkout counter, cashiers or tills. Increasing the amount of goods a shopper can collect increases the quantities they are likely to purchase in a single trip, boosting store profitability.</p>
</div>
{% endif %}
{% if user.is_authenticated %}
<div class="container">
    <div class="row mx_auto">
    {% for product in products.object_list %}
    <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
        <div class="card text-center">
            <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.img.url}}" alt="{{product.name}}" style="width:350px;height:350px;"></a>
        </div>
        <div class="card-body">
            <h4>{{product.name}}</h4>
            <p>{{product.price}}</p>
        </div>
    </div>
    {% endfor %}
    </div>
    <div class="mx_auto">
        {% if products.paginator.num_pages %}
        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-lightmbtn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
</div>
{% endif %}
    <br>
{% endblock %}

app/templates/footer.html
<div>
    <div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy:All In Bloom pvt ltd. All rights Reserved</p>
    </div>
</div>

app/templates/header.html
{% load static %}
<header>
    <center>
            <a href="{% url 'shopapp:allProdCat' %}">
            <img src="{% static 'img/Logo.png' %}" alt="logoimage" width="100px" height="100px;">
    </center>
</header>

app/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   {% if category %}
     {{category.desc|truncatewords:155}}
   {% else %}
    Welcome to All In Bloom Collections where you can buys different items...
   {% endif %}
{% endblock %}

{% block title %}
  {% if category %}
     {{category.name}} - All in Bloom Collections
  {% else %}
  See our New Collections - All in Bloom Collections
  {% endif %}
{% endblock %}
{% block content %}


<div class="container py-5">
    <h1>Login</h1>
    <form method="post">
       {% csrf_token %}
    <input type="text" name="username" placeholder="username"><br>
    <input type="password" name="password" placeholder="Enter your password"><br>
    <button class="btn btn-primary" type="submit">Login</button>

    </form>
    {% for msg in messages %}
<h2>{{msg}}</h2>
{% endfor %}
    <p class="text-center">Don't have an account?,  <a href="{% url 'RegistrationView' %}">create an account</a></p>

</div>

{% endblock %}


<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>login</title>-->
<!--</head>-->
<!--<body style="background-color:tomato;text-align:center;font-size:160%;background-image:url('banner.png');padding:14px;">-->
<!--<h2 style="background-color:blue;text-align:center">WELCOME TO ALL IN BLOOM LOGIN</h2>-->

<!--<form action="{% url 'login_user' %}" method="POST">-->
<!--    {% csrf_token %}-->

<!--    <input type="text" name="username" placeholder="username"><br>-->
<!--    <input type="password" name="password" placeholder="Enter your password"><br>-->
<!--    <input type="submit">-->
<!--</form>-->
<!--</body>-->
<!--</html>-->

app/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'shopapp:allProdCat' %}">Home</a>
        </li>

        <li class="nav-item dropdown {% if 'shopapp' in request.path %} active {% endif %}">

          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>

          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'shopapp:allProdCat' %}">All Products</a></li>

             {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>

              {% endfor %}

          </ul>
        </li>

        {% if item_count > 0 %}

        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fa fa-shopping-cart"></i></a>
        </li>
        {% endif %}


{% if user.is_authenticated %}
           {% if user.customer.membership == True %}
          <a class="btn btn-primary ml-lg-3" href="{% url 'subscription_app:settings' %}">Premium</a>
        {% else %}
          <a class="btn btn-primary ml-lg-3" href="{% url 'subscription_app:join' %}">subscribe</a>
        {% endif %}
          <li class="nav-item">
          <a class="nav-link" href="{% url 'LogoutView' %}">Logout</a>
        </li>

{% else %}

        <li class="nav-item">
          <a class="nav-link" href="{% url 'RegistrationView' %}">Registration</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'LoginView' %}">Login</a>
        </li>


{% endif %}

<!--       {% if user.is_authenticated %}-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link" href="{% url 'shopapp:allProdCat' %}">Subscription</a>-->
<!--        </li>-->
<!--        {% endif %}-->
      </ul>
      <form class="d-flex" action="{% url 'search_app:SearchResult' %}" method="get">
        {% csrf_token %}
          {% if user.is_authenticated %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>

          {% endif %}
      </form>

    </div>
  </div>
</nav>

app/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
     {{product.desc|truncatewords:155}}
{% endblock %}

{% block title %}
  {% if category %}
     {{product.name}} - All In Bloom store
  {% endif %}
{% endblock %}

{% block content %}
<div class="row my_prod_row_class">
    <div class="mx_auto">
        <p><a href="{% url 'shopapp:allProdCat' %}">Home</a>|<a href="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}}</p>
    </div>
</div>
<div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem;">
            <img src="{{product.img.url}}" alt="{{product.name}}" width="300px" height="300px;">
        </div>
    </div>

        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
            <h1 class="my_prod-title">{{product.name}}</h1>
            <p>${{product.price}}</p>
            <p class="my_title">product description</p>
            <p class="text-justify my-prod-text">{{product.desc}}</p>
            {% if product.stock <= 0 %}
            <p class="text-justify my-prod-text"><b>Out of Stock</b></p>
            {% else %}

            <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a>
<!--                 <a href="{% url 'subscription_app:index' %}" class="btn btn-success btn-block my_custom_button"><button>Subscription</button></a>-->
<!--        {% if user.customer.membership == True %}-->
<!--          <a class="btn btn-primary ml-lg-3" href="{% url 'subscription_app:settings' %}">Premium</a>-->
<!--        {% else %}-->
<!--          <a class="btn btn-primary ml-lg-3" href="{% url 'subscription_app:join' %}">subscribe</a>-->
<!--        {% endif %}-->
            {% endif %}

        </div>
    </div>
</div>
</div>
<br>
<br>
{% endblock %}

app/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   {% if category %}
     {{category.desc|truncatewords:155}}
   {% else %}
    Welcome to All In Bloom Collections where you can buys different items...
   {% endif %}
{% endblock %}

{% block title %}
  {% if category %}
     {{category.name}} - All in Bloom Collections
  {% else %}
  See our New Collections - All in Bloom Collections
  {% endif %}
{% endblock %}
{% block content %}

<div class="container py-5">
    <h1>Register</h1>
    <form method="post">
       {% csrf_token %}
    <input type="text" name="username" placeholder="username"><br>
    <input type="text" name="first_name" placeholder="Enter your first name"><br>
    <input type="text" name="last_name" placeholder="Enter your last name"><br>
    <input type="email" name="email" placeholder="Enter your email"><br>
    <input type="password" name="password" placeholder="Enter your password"><br>
    <input type="password" name="password1" placeholder="Conform your password"><br>
    <button class="btn btn-primary" type="submit">Register</button>

    </form>
    {% for msg in messages %}
<h2>{{msg}}</h2>
{% endfor %}
    <p class="text-center">If you already have an account,  <a href="{% url 'LoginView' %}">login</a>  instead </p>

</div>

{% endblock %}



<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Registration</title>-->
<!--</head>-->

<!--<body style="background-color:tomato;text-align:center;font-size:160%;background-image:url('banner.png');padding:14px;">-->

<!--<h2 style="background-color:blue;text-align:center">WELCOME TO ALL IN BLOOM REGISTRATION</h2>-->

<!--<form action="{% url 'register_user' %}" method="POST">-->
<!--    {% csrf_token %}-->
<!--    <input type="text" name="username" placeholder="username"><br>-->
<!--    <input type="text" name="first_name" placeholder="Enter your first name"><br>-->
<!--    <input type="text" name="last_name" placeholder="Enter your last name"><br>-->
<!--    <input type="email" name="email" placeholder="Enter your email"><br>-->
<!--    <input type="password" name="password" placeholder="Enter your password"><br>-->
<!--    <input type="password" name="password1" placeholder="Conform your password"><br>-->
<!--    <input type="submit">-->
<!--</form>-->
<!--{% for msg in messages %}-->
<!--<h2>{{msg}}</h2>-->
<!--{% endfor %}-->
<!--</body>-->
<!--</html>-->

app/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
     We have variety of products..
{% endblock %}

{% block title %}
  Search
{% endblock %}

{% block content %}
<div>
    <p class="text-center my_search_text"> You have searched for: <b>"{{query}}"</b></p>
</div>
<div class="container">
    <div class="row mx_auto">
    {% for product in products %}
    <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
        <div class="card text-center" style="min-width:18rem;">
            <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.img.url}}" alt="{{product.name}}" style="width:1290px;height:350px;"></a>
        </div>
        <div class="card-body">
            <h4>{{product.name}}</h4>
            <p>{{product.price}}</p>
        </div>
    </div>
        {% empty %}
        <div class="row mx_auto">
            <p class="text-center my_search_text">zero results found</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}